import { NextResponse } from "next/server";
import type { EcosystemParticipant } from "@/types/telemetry";

const CROSS_SITE_PARTICIPANTS: EcosystemParticipant[] = [
  {
    id: "ezra-haugabrooks",
    name: "Ezra Haugabrooks",
    email: "ezra.haugabrooks@gmail.com",
    discipline: "Viola Performance / Orchestra Member",
    subdomainSource: "orchestra",
    location: "Milwaukee, WI / Atlanta, GA",
    educationHistory: "Black Diaspora Symphony Orchestra (2025 Concert Member)",
    culturalCapitalNotes: "Confirmed Violist for BDSO annual memorial concert. Uncompensated rehearsal hours & musical labor.",
    uncompensatedRehearsalHours: 36,
    status: "Confirmed",
    orchestraRecord: {
      project: "Black Diaspora Symphony Orchestra - 2025 Annual Concert",
      instrument: "Viola",
      status: "Confirmed",
      headshotUrl: "https://link.storjshare.io/raw/jv56mcbz6f3ebhsnssa5tqlncpfa/orchestabeam/Images%2FBlack%20Diaspora%20Symphony%2F2025%20Annual%20Concert%2FMusican%20photos/IMG_9498.jpg",
      notes: "Violist first year playing with Black Diaspora Symphony Orchestra.",
    },
  },
  {
    id: "dayvin-hallmon",
    name: "Dayvin Hallmon",
    email: "hello@beamcenter.org",
    discipline: "Founder & Conductor / Artistic Director",
    subdomainSource: "orchestra",
    location: "Milwaukee, WI",
    educationHistory: "Black Diaspora Symphony Orchestra (Founder)",
    culturalCapitalNotes: "Conductor for the 2025 Annual Memorial Concert. Founder celebrating African diaspora composers.",
    uncompensatedRehearsalHours: 120,
    status: "Confirmed",
    orchestraRecord: {
      project: "Black Diaspora Symphony Orchestra - 2025 Annual Concert",
      instrument: "Conductor",
      status: "Confirmed",
      notes: "Artistic director & conductor for BDSO 2025 Memorial Concert.",
    },
  },
  {
    id: "nicole-gabriel",
    name: "Nicole Gabriel",
    email: "ngabriel.nicole@gmail.com",
    discipline: "Viola Section",
    subdomainSource: "orchestra",
    location: "Milwaukee, WI",
    educationHistory: "BDSO Juneteenth Concert ('Cries from Our Soil')",
    culturalCapitalNotes: "Performed in 2024 Juneteenth Concert; returning violist for 2025 Memorial Concert.",
    uncompensatedRehearsalHours: 24,
    status: "Confirmed",
    orchestraRecord: {
      project: "Black Diaspora Symphony Orchestra - 2025 Annual Concert",
      instrument: "Viola",
      status: "Confirmed",
    },
  },
  {
    id: "korinthia-klein",
    name: "Korinthia Klein",
    email: "kory@korinthianviolins.com",
    discipline: "Viola Section / Luthier",
    subdomainSource: "orchestra",
    location: "Milwaukee, WI",
    educationHistory: "Korinthian Violins (Owner & Master Luthier)",
    culturalCapitalNotes: "Owner of Korinthian Violins; confirmed to play viola in BDSO concert.",
    uncompensatedRehearsalHours: 24,
    status: "Confirmed",
    orchestraRecord: {
      project: "Black Diaspora Symphony Orchestra - 2025 Annual Concert",
      instrument: "Viola",
      status: "Confirmed",
    },
  },
  {
    id: "autumn-reed",
    name: "Autumn Maria Reed",
    email: "amreed8@gmail.com",
    discipline: "Double Bass & Cello / Performer & Educator",
    subdomainSource: "orchestra",
    location: "Madison, WI",
    educationHistory: "Performer, educator, and composer (amreed8.com)",
    culturalCapitalNotes: "Double bassist for BDSO; performs cello with Black String Triage Ensemble.",
    uncompensatedRehearsalHours: 32,
    status: "Confirmed",
    orchestraRecord: {
      project: "Black Diaspora Symphony Orchestra - 2025 Annual Concert",
      instrument: "Double Bass",
      status: "Confirmed",
    },
  },
  {
    id: "brenda-rodrigues",
    name: "Brenda Rodrigues",
    email: "rodr2484@uwm.edu",
    discipline: "Violin I Section",
    subdomainSource: "orchestra",
    location: "Milwaukee, WI (UWM)",
    educationHistory: "University of Wisconsin-Milwaukee",
    culturalCapitalNotes: "Violinist at UWM confirmed for BDSO 2025 concert.",
    uncompensatedRehearsalHours: 20,
    status: "Confirmed",
    orchestraRecord: {
      project: "Black Diaspora Symphony Orchestra - 2025 Annual Concert",
      instrument: "Violin I",
      status: "Confirmed",
    },
  },
  {
    id: "churchill-caruthers",
    name: "Churchill Caruthers Jr",
    email: "churchillcaruthers@gmail.com",
    discipline: "Violin I Section",
    subdomainSource: "orchestra",
    location: "Milwaukee, WI",
    educationHistory: "Independent Musician",
    culturalCapitalNotes: "Violinist located in Milwaukee; interested in playing in December concert.",
    uncompensatedRehearsalHours: 12,
    status: "Interested",
    orchestraRecord: {
      project: "Black Diaspora Symphony Orchestra - 2025 Annual Concert",
      instrument: "Violin I",
      status: "Interested",
    },
  },
  {
    id: "zack-munoz",
    name: "Zack Munoz",
    email: "zacklmunoz123@gmail.com",
    discipline: "Flute Section",
    subdomainSource: "orchestra",
    location: "Milwaukee, WI",
    educationHistory: "MYSO Senior Symphony",
    culturalCapitalNotes: "MYSO Senior Symphony flutist; Cuban-Mexican-Puerto Rican heritage; played in 2023 BDSO concert.",
    uncompensatedRehearsalHours: 24,
    status: "Confirmed",
    orchestraRecord: {
      project: "Black Diaspora Symphony Orchestra - 2025 Annual Concert",
      instrument: "Flute",
      status: "Confirmed",
    },
  },
];

export async function GET() {
  return NextResponse.json({
    totalCount: CROSS_SITE_PARTICIPANTS.length,
    participants: CROSS_SITE_PARTICIPANTS,
  });
}
